# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 19:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_bouncy', '0004_increase_processing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounce',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
