# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bouncy', '0005_auto_20171206_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounce',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='headers',
        ),
        migrations.AddField(
            model_name='bounce',
            name='dump',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='dump',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='dump',
            field=models.TextField(blank=True, null=True),
        ),
    ]
